/**
 * POST /api/verse-tts
 * Body: { text: string; voice?: string }
 * Streams back an MP3 audio buffer generated by OpenAI TTS.
 *
 * Available voices: alloy | echo | fable | onyx | nova | shimmer
 * Default: nova (warm, natural female voice)
 */
import { NextRequest, NextResponse } from "next/server";
import { rateLimit, getClientIp } from "@/lib/rateLimit";

const VALID_VOICES = ["alloy", "echo", "fable", "onyx", "nova", "shimmer"] as const;
type TTSVoice = typeof VALID_VOICES[number];

export async function POST(req: NextRequest) {
  // Rate limit: 15 TTS requests per minute per IP
  const ip = getClientIp(req);
  const rl = rateLimit(ip, { limit: 15, windowMs: 60_000 });
  if (!rl.allowed) {
    return NextResponse.json(
      { error: "Too many requests." },
      { status: 429, headers: { "Retry-After": String(Math.ceil((rl.resetMs - Date.now()) / 1000)) } }
    );
  }

  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return NextResponse.json({ error: "TTS not configured" }, { status: 500 });
  }

  let text: string;
  let voice: TTSVoice;
  try {
    const body = await req.json();
    text  = (body.text  ?? "").trim().slice(0, 4096);
    const raw = (body.voice ?? "nova").toLowerCase();
    voice = VALID_VOICES.includes(raw as TTSVoice) ? (raw as TTSVoice) : "nova";
    if (!text) throw new Error();
  } catch {
    return NextResponse.json({ error: "Provide text" }, { status: 400 });
  }

  try {
    const res = await fetch("https://api.openai.com/v1/audio/speech", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "tts-1",
        input: text,
        voice,
        response_format: "mp3",
      }),
      signal: AbortSignal.timeout(30_000),
    });

    if (!res.ok) {
      const err = await res.text();
      console.error("[verse-tts] OpenAI error:", err);
      return NextResponse.json({ error: "TTS failed" }, { status: 502 });
    }

    // Stream the MP3 directly back to the client
    const audioBuffer = await res.arrayBuffer();
    return new NextResponse(audioBuffer, {
      status: 200,
      headers: {
        "Content-Type": "audio/mpeg",
        "Cache-Control": "private, max-age=86400",
      },
    });
  } catch (err) {
    console.error("[verse-tts] error:", err);
    return NextResponse.json({ error: "Request failed" }, { status: 500 });
  }
}
